### ISSUE TITLE
Pet Peeve Survey

### ISSUE THREAD

**Issue by vmbrasseur** [vmbrasseur/10stepprogram#8]
Should we perhaps put together a survey "What are your pet peeves for things that conference presenters do?" then pitch it to social network to get more actionable and relevant ideas which would (potentially) appeal to our audience?

**Comment by jberkus** [comment]
Hmmm.  Can you explain more? Not really picturing this.  Could be lack of coffee ...

**Comment by jberkus** [comment]
OK, now that I've looked at the outline, I'm getting this.  However, I kinda think that "pet peeve" is the wrong approach.  How about this?

"Please select the bad speaker behaviors which ruined an otherwise good presentation you watched in the last year."

That is, we're not looking for "what annoys you", but "what things killed a preso you liked?"  Does this make sense?

**Comment by vmbrasseur** [comment]
I think you're getting too wrapped up in the terminology I used, but yup, that's the idea I meant. :)

**Comment by jberkus** [comment]
Oh ok!  In that case, here's a suggested set of questions/answers:

Do you give technical presentations, or just attend them?
give and attend | just attend | don't attend (please skip survey)

Roughly how many technical conferences did you attend in the last year?
0 | 1-2 | 3-6 | more than 6

Roughly how many other technical presentations did you see in the last year (user groups, webinars, company presentations, etc.)?
0 | 1-5 | 6-20 | more than 20

Thinking of the presentations you attended with topics and/or speakers you liked, what speaker behaviors below do you feel substantially detracted from, or even ruined, an otherwise good presentation?  Check all that apply.
- Saying "um" a lot
- Running over or under time
- Technical issues with AV/Internet
- Demo failure
- Couldn't hear/understand speaker
- Bored/tired/distracted speaker
- Bad/offensive jokes/content
- Unreadable slides
- Unreadable code
- Presentation didn't match description
- Too high/low level for the audience
- Incomplete presentation
- Weird/distracting body language
- Interruptions/heckling from audience
- Other: [    ]

If you could magically eliminate just one bad speaker behavior from all presenters everywhere, which one would it be?  (same list as previous)

**Comment by vmbrasseur** [comment]
Here's a draft of a survey:

https://docs.google.com/forms/d/1hsnfG_HXfkJxlHFIarvN5H5SSe6OFPTdnE1DCLftP-8/viewform

Any changes needed?

**Comment by jberkus** [comment]
Looks good!

One addition: we should let people know at the beginning of the survey that it's only a 7 question survey, so they're more likely to complete it.

**Comment by vmbrasseur** [comment]
Fixed.

Link to the public (live) form: https://docs.google.com/forms/d/1hsnfG_HXfkJxlHFIarvN5H5SSe6OFPTdnE1DCLftP-8/viewform?usp=send_form

Let's each tweet it out tomorrow?

**Comment by jberkus** [comment]
Sure.  Also FB, and a couple lists.

**Comment by vmbrasseur** [comment]
I tweeted this morning. Results are [in this sheet](https://docs.google.com/spreadsheets/d/1KS-0tiIrXWSGr3bDGkRTdgmSWZLSmLMCBCLtWhURcPM/edit?usp=sharing)

**Comment by vmbrasseur** [comment]
We have 61 submissions so far. It would be great to have more (a nice, round 100?). I'll tweet again tomorrow morning and see whether we can't get to 80 or so by the end of the day.

**Comment by jberkus** [comment]
I'll try Google Plus tommorrow.

**Comment by vmbrasseur** [comment]
Woo. 15 more responses today (78 total). That's a goodly amount of data, none of which I've looked at yet.

**Comment by jberkus** [comment]
I'll pump out some data analysis once we're done collecting responses.

Hey, can you get Josh Simmons to broadcast the survey?  I'll ask Gareth.

**Comment by jberkus** [comment]
Just reached 100

**Comment by jberkus** [comment]
I need to digest the stats on this.

**Comment by vmbrasseur** [comment]
@jberkus' [write up of the results](http://www.databasesoup.com/2015/12/speaker-practice-survey.html).

I've shut down the survey & put ^^ that link in the "no longer accepting responses" message.
